---
title: "Scraper"
output: html_notebook
---

```{r setup}
library(tidyverse)
library(rvest)
library(stringr)
library(readxl)

# Helper function to clean the legislator's name
# NO LONGER NEEDED
name_cleaner <- function(name){
  name <- gsub("U.S. Representative", "", name)
  name <- gsub("Representative", "", name)
  name <- gsub("U.S. Congressman", "", name)
  name <- gsub("U.S. Congresswoman", "", name)
  name <- gsub("Congressman", "", name)
  name <- gsub("Congresswoman", "", name)
  name <- gsub("Home - ", "", name)
  name <- gsub("\\s*,?\\s*(D\\.D\\.S\\.|PhD|M\\.D\\.|M\\.Sc\\.|LL\\.M\\.|
               J\\.D\\.|B\\.Sc\\.|D\\.Phil\\.|Ed\\.D\\.|M\\.Eng\\.|\\w{1,3}
               \\.\\w{1,3}\\.)", "", name) # Remove degrees but keep things like Jr.
  name <- str_trim(name)
  
  return(name)
}
```

# Scraper v2

Helpers
```{r}
# Helper function to detect date formats for a list of strings
detect_date_formats <- function(date_strings) {
  # A list of candidate formats (date-only and datetime variants)
  candidate_formats <- c(
    "%Y-%m-%dT%H:%M:%S",   # ISO 8601 with T separator
    "%Y-%m-%d %H:%M:%S",   # Common datetime with space separator
    "%Y-%m-%d",            # ISO date
    "%d/%m/%Y %H:%M:%S",   # Day/Month/Year with datetime
    "%d/%m/%Y",            # Day/Month/Year
    "%m/%d/%Y %H:%M:%S",   # Month/Day/Year with datetime
    "%m/%d/%Y",            # Month/Day/Year
    "%Y/%m/%d %H:%M:%S",   # Year/Month/Day with datetime using slash
    "%Y/%m/%d",            # Year/Month/Day with slash
    
    # Full month name formats like "September 23, 2020"
    "%B %d, %Y",
    "%B %d, %Y %H:%M:%S",

    # Abbreviated month name formats like "Sep 23, 2021" (without a period)
    "%b %d, %Y",
    "%b %d, %Y %H:%M:%S",
    
    # Abbreviated month name with a period: "Sep. 23, 2021"
    "%b. %d, %Y",
    "%b. %d, %Y %H:%M:%S"
  )
  
  # For each string in date_strings, find the first format (if any) that parses successfully
  sapply(date_strings, function(ds) {
    fmt_found <- NA_character_
    
    for (fmt in candidate_formats) {
      parsed <- suppressWarnings(strptime(ds, format = fmt))
      if (!is.na(parsed)) {
        fmt_found <- fmt
        break
      }
    }
    
    fmt_found
  })
}

detect_pr_link_format <- function(strings, home_link, pr_page_link) {

  #path_pattern <- "^/[[:alnum:]._/-]+$"
  url_pattern  <- "^https?://[[:alnum:]._/-]+$"
  
  retVal <- sapply(strings, 
             FUN=function(x){
                            if(grepl(url_pattern, x)) x
                            else if(substr(x, 1, 19)=="documentsingle.aspx"){
                              x <- paste0(sub("documentquery\\.aspx.*", "", pr_page_link),
                                          x)
                            }
                            else{
                              if(substr(x, 1, 1)!= "/") x <- paste0("/", x)
                              # if overlap between x and pr_page_link
                                # merge
                              else paste0(pr_page_link, x)
                            }
                            })
  
  names(retVal) <- NULL
  
  return(retVal[!is.na(retVal)])
}


detect_pr_link_format(c("documentsingle.aspx?DocumentID=4060"),
                      c("https://mikerogers.house.gov"),
                      c("https://mikerogers.house.gov/news/documentquery.aspx?DocumentTypeID=27"))

grepl("^/[[:alnum:]._/-]+$","documentsingle.aspx?DocumentID=4060")

# detect_pr_link_format(c("https://schweikert.house.gov/2025/02/13/four-key-moments-hearing-on-the-lack-of-return-on-investment-from-irs-funding-and-the-need-for-agency-modernization/"), "https://schweikert.house.gov")
```

Main functions

## Presser page finder
```{r}
presser_page_finder <- function(link, debug=F){
  page <- read_html(link)
  
  # XPath explanation:
  # - //a selects all <a> elements.
  # - translate(., 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz') converts the text to lowercase.
  # - The first condition checks if the text contains "press release".
  # - The second condition checks if the text contains "news" but not "newsletter".
  # - The and @href part ensures that only nodes with an href attribute are selected.
  link_node <- html_element(
    page,
    xpath = "//a[
    (
      contains(translate(., 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz'), 'press release')
      or
      (
        contains(translate(., 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz'), 'news')
        and
        not(contains(translate(., 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz'), 'newsletter'))
      )
    )
    and @href
  ]"
  )
  
  if (!is.null(link_node)) {
    href_value <- html_attr(link_node, "href")
  } else {
    message("No relevant link found.")
  }
  
  return(href_value)
}
```

## Node hunter
```{r}
# Loops through known nodes for elements (titles, dates, PR links and text)
node_hunter <- function(link, debug=F){
  
  # Check if link has https:// at the start, if not add it
  if(substr(link, 1, 8)!="https://") link <- paste0("https://", link)
  
  # Check if link is in valid format and date range is valid
  if(!grepl("https://[a-zA-Z0-9\\-]+\\.house\\.gov", link)){
    stop("Link is not of the form \"{name}.house.gov\" or \"https://{name}.house.gov\"")
  }
  
  # Sanitize input by removing extra forward slash at end of URL if present
  if(substr(link, nchar(link), nchar(link))=="/") link <- substr(link, 1, nchar(link)-1)
  
  # Find the link for the press release page
  pr_page_link <- presser_page_finder(link, debug=debug)
  
  if(is.na(link)) stop(paste0("Press release page could not be found for ", link))
  
  # Build the URL for the press releases page
  if (!grepl("^https?://", pr_page_link)) {
    # Remove trailing slashes from link
    base_link <- sub("/+$", "", link)
    
    # Remove leading slashes from pr_page_link
    relative_link <- sub("^/+", "", pr_page_link)
    
    # Combine with a single slash between them
    pr_page_link <- paste0(base_link, "/", relative_link)
  }
  
  # Save PR page home to return later
  pr_page_link_home <- pr_page_link
  
  # Read in our webpage elements to look through
  nodes <- read_excel("nodes.xlsx")
  
  ## FINDING PAGINATION FORMAT
  
  pagination <- nodes %>% filter(element=="page link")
  
  page_index_start <- NA
  page_string <- NA
  
  # Loop through press release page link formats until one works, then determine
  # if the pagination starts at 0 or 1
  for(p in pagination$string){
    page0 <- try(read_html(paste0(pr_page_link, p, 0)), silent=T)
    page1 <- try(read_html(paste0(pr_page_link, p, 1)), silent=T)
    
    # A non-blank page will have length > 1
    if(length(page0)==1 & length(page0)==1) next
    else if(length(page1)==2){ page_index_start <- 1; page_string <- p; break }
    else if(length(page0)==2){ page_index_start <- 0; page_string <- p; break }
  }
  
  if(is.na(page_string)) stop(paste0("Pagination failed for ", link))
  
  # Build the press release page URL
  pr_page_link <- paste0(pr_page_link, page_string, page_index_start)
  
  if(debug) message("URL: ", pr_page_link)
  
  ## FINDING DATE LINK NODE
  
  date_nodes <- nodes %>% filter(element=="dates")
  date_node <- NA
  date_node_type <- NA
  date_formats <- NA
  date_attempt <- character(0) # Not NA b/c we differentiate successes by length
                               # Might have a page with 1 presser
  print("here1")
  # Loop through date nodes until one works
  for(i in 1:nrow(date_nodes)){
    # Case when date can be found with xpath
    if(date_nodes$type[i]=="xpath"){
      date_attempt <- try(read_html(pr_page_link) %>% 
                          html_elements(xpath=date_nodes$string[i]) %>% 
                            html_text() %>% str_trim(), silent=T)
    }
    # Case when date can be found with CSS
    else{
      date_attempt <- try(read_html(pr_page_link) %>% 
                            html_elements(date_nodes$string[i]) %>% 
                            html_text() %>% str_trim(), silent=T)
    }
    traceback()
    print("here2")
    if(length(date_attempt)==0 | inherits(date_attempt, "try-error")) next
    else{
      # Detect the format of each scraped date
      date_formats <- detect_date_formats(date_attempt)
      
      # If they're all NA then try next node
      if(all(is.na(date_formats))) next
      # Otherwise we have our date node
      else{
        date_node <- date_nodes$string[i]
        date_node_type <- date_nodes$type[i] 
        break
      }
    }
  }
  
  if(all(is.na(date_formats))) stop(paste0("No valid date node found for ", link))
  
  if(debug) message("Date node: ", date_node, 
                    "\nDate formats: ", paste(date_formats, collapse=" | "))
  
  ## FINDING TITLE LINK NODE
  
  title_nodes <- nodes %>% filter(element=="titles")
  title_node <- NA
  title_node_type <- NA
  title_attempt <- character(0)
  
   # Loop through title nodes until one works
  for(i in 1:nrow(title_nodes)){
    
    # Case when title can be found with xpath
    if(title_nodes$type[i]=="xpath"){
      title_attempt <- try(read_html(pr_page_link) %>% 
                          html_elements(xpath=title_nodes$string[i]) %>% 
                            html_text() %>% str_trim(), silent=T)
    }
    # Case when title can be found with CSS
    else{
      title_attempt <- try(read_html(pr_page_link) %>% 
                            html_elements(title_nodes$string[i]) %>% 
                             html_text() %>% str_trim(), silent=T)
    }

    if(length(title_attempt)<1 | inherits(title_attempt, "try-error")) next 
    else{
      title_node <- title_nodes$string[i]
      title_node_type <- title_nodes$type[i]
      break
    }
  }
  
  if(is.na(title_node)) stop(paste0("No valid title node found for ", link))
  
  if(debug) message("Title node: ", title_node)
  
  ## FINDING PR LINK NODE
  
  pr_link_attempt <- NA
  
  # Usually press release links are hyperlinked in the title so try that first
  pr_link_attempt <- try(read_html(pr_page_link) %>% 
                            html_elements(title_node) %>% html_attr("href") %>% 
                            str_trim(), silent=T)
  
  # If grabbing using the title node didn't work then loop through known
  # PR link nodes
  if(all(is.na(pr_link_attempt)) | inherits(pr_link_attempt, "try-error")){
    pr_link_nodes <- nodes %>% filter(element=="links")
    pr_link_node <- NA
    pr_link_attempt <- character(0)
    
    # Loop through PR link nodes until one works
    for(i in 1:nrow(pr_link_nodes)){
      
      # Case when date can be found with xpath
      if(pr_link_nodes$type[i]=="xpath"){
        pr_link_attempt <- try(read_html(pr_page_link) %>% 
                            html_elements(xpath=pr_link_nodes$string[i]) %>% 
                              html_text() %>% str_trim(), silent=T)
      }
      # Case when PR link can be found with CSS
      else{
        pr_link_attempt <- try(read_html(pr_page_link) %>% 
                               html_elements(pr_link_nodes$string[i]) %>% 
                               html_attr("href") %>% str_trim(), silent=T)
      }
  
      if(length(pr_link_attempt)<1 | inherits(pr_link_attempt, "try-error")) next 
      else{
        pr_link_node <- pr_link_nodes$string[i]
        pr_link_node_type <- pr_link_nodes$type[i]
        break
      }
    }
    
  }
  # Otherwise PR link node and type are same as title
  else{
    pr_link_node <- title_node
    pr_link_node_type <- title_node_type
  }
  
  if(debug) message("PR link node:", pr_link_node)
  
  print(pr_link_attempt)
  
  # Check if each PR link is a path, a URL, or neither
  # Remove elements that are neither, turn paths into full URLs
  pr_link_attempt <- detect_pr_link_format(pr_link_attempt, link, pr_page_link)
  
  if(debug) message("Example PR link: ", pr_link_attempt[1])
  
  
  # Check to make sure we have the same number of successfully parsed dates,
  # titles, and PR links
  # If not, then throw an error because something went wrong
  if(length(unique(c(sum(is.na(date_attempt)),  # Cheeky way to test equality of
                     sum(is.na(title_attempt)), # multiple values
                     sum(is.na(pr_link_attempt)))
                   ))!=1){
    if(debug){
      message("Dates: ", paste(date_attempt, collapse=" | "), "\n",
              "Titles:", paste(title_attempt, collapse=" | "), "\n",
              "Links: ", paste(pr_link_attempt, collapse=" | "))
    }
    stop("Number of dates, titles, and/or PR links does not match.")
  }
  
  ## FINDING PR TEXT NODE
  
  text_nodes <- nodes %>% filter(element=="text")
  text_link <- pr_link_attempt[1]
  text_node <- NA
  text_node_type <- NA
  text_attempt <- NA
  
  # Loop through text nodes until one works
  for(i in 1:nrow(text_nodes)){
    
    # Case when text can be found with xpath
    if(text_nodes$type[i]=="xpath"){
      text_attempt <- try(read_html(text_link) %>% 
                          html_element(xpath=text_nodes$string[i]) %>% 
                            html_text() %>% str_trim(), silent=T)
    }
    # Case when text can be found with CSS
    else{
      text_attempt <- try(read_html(text_link) %>% 
                            html_element(text_nodes$string[i]) %>% 
                             html_text() %>% str_trim(), silent=T)
    }
    
    if(is.na(text_attempt) | length(text_attempt)<1 | 
       inherits(text_attempt, "try-error")) next 
    else{
      text_node <- text_nodes$string[i]
      text_node_type <- text_nodes$type[i]
      break
    }
  }
  
  if(is.na(text_node)) stop(paste0("No valid PR text node found for ", link))
  
  if(debug) message("Text node: ", text_node)
  
  return(list(homepage_link=link,
              pr_page_link=pr_page_link_home,
              page_string=page_string,
              page_index_start=page_index_start,
              date_node=date_node,
              date_node_type=date_node_type,
              date_format=date_formats[1],
              title_node=title_node,
              title_node_type=title_node_type,
              pr_link_node=pr_link_node,
              pr_link_node_type=pr_link_node_type,
              text_node=text_node,
              text_node_type=text_node_type
              ))
  
}

# node_hunter(link="schweikert.house.gov", debug=T)

node_hunter(link="mikerogers.house.gov", debug=T)
```

```{r}
#read_html("https://mikerogers.house.gov/news/documentsingle.aspx?DocumentID=4060") %>% 
read_html("https://mikerogers.house.gov/news/documentquery.aspx?DocumentTypeID=27") %>% 
  html_elements(".newsie-titler a") %>% html_attr("href")
```

## Member scraper
```{r}
# Recursively scrapes data for a single member
member_scraper <- function(info, start_date, end_date, page_index=0,
                           pressers=data.frame(date=c(), title=c(), 
                                               body=c(), tags=c(), url=c()),
                           page_limit=1000,
                           clean_text=F, # TODO: add option to have clean and raw text
                           debug=F, progress=T){
  
  # Store scraping info in individual variables to make life easier
  homepage_link <- info$homepage_link
  pr_page_link <- info$pr_page_link
  page_string <- info$page_string
  page_index_start <- info$page_index_start
  date_node <- info$date_node
  date_node_type <- info$date_node_type
  date_format <- info$date_format
  title_node <- info$title_node
  title_node_type <- info$title_node_type
  pr_link_node <- info$pr_link_node
  pr_link_node_type <- info$pr_link_node_type
  text_node <- info$text_node
  text_node_type <- info$text_node_type
  
  # Data frame that will hold scraped pressers
  pressers <- data.frame(date=c(), title=c(), body=c(), tags=c(), url=c())

  if(page_index>page_limit){
    message("Page limit reached for: ", homepage_link)
    return(pressers)
  }
  
  page_index <- ifelse(page_index_start==0, page_index_start, page_index)
  
  if(progress) message(ifelse(debug, "", "\014"), "Scraping pressers from: ", homepage_link, 
                       "    ", "pg: ", page_index)
  
  current_page <- read_html(paste0(pr_page_link, page_string, page_index))

  # dates <- ifelse(date_node_type=="css", html_elements(current_page, date_node), 
  #                 html_elements(current_page, xpath=date_node)) %>% 
  #   html_text() %>% str_trim()
  
  if(date_node_type=="css") dates <- current_page %>% html_elements(date_node)
  else dates <- current_page %>% html_elements(xpath=date_node)
  
  dates <- dates %>% html_text() %>% str_trim()
  
  # Handle empty page case, i.e. when all the pages have been checked
    if(length(dates)==0) return(pressers)

    # Format the dates
    dates <- sapply(dates, 
                    function(x) as.character(strptime(x, f <- date_format, 
                                                      tz = "")))

    if(head(dates, 1) > end_date & tail(dates, 1) > end_date){
      # Haven't reached a page in our date range; recurse on the next page
      return(rbind(pressers, member_scraper(info, start_date, end_date,
                                            page_index + 1, pressers, 
                                            page_limit, clean_text, 
                                            debug, progress)))
    }
    else if(head(dates, 1) < start_date){
      # Base case: stop paginating
      return(pressers)
    }
    else{
      # Page has pressers in our date range--scrape them then recurse on next page

      # Get indexes for the dates within our range
      desired_dates <- which(dates >= start_date & dates <= end_date)

      # If there are pressers from the desired date range on the page then
      # get all the data we want
      if(length(desired_dates)>0){
        
        # Get titles
        if(title_node_type=="css") titles <- current_page %>% html_elements(title_node)
        else titles <- current_page %>% html_elements(xpath=title_node)
        
        titles <- titles %>% html_text() %>% str_trim()
        
        # Get PR links
        if(pr_link_node_type=="css") pr_links <- current_page %>% html_elements(pr_link_node)
        else pr_links <- current_page %>% html_elements(xpath=pr_link_node)
        
        pr_links <- pr_links %>% html_attr("href")
        
        # Subset to only pressers within date range
        titles <- titles[desired_dates]
        pr_links <- pr_links[desired_dates]
        
        # Build the PR URLs
        pr_links <- detect_pr_link_format(pr_links, homepage_link, pr_page_link)

        texts <- sapply(pr_links, 
                          FUN=function(l){
                            if(text_node_type=="css") texts <- read_html(l) %>% html_elements(text_node)
                            else texts <- read_html(l) %>% html_elements(xpath=text_node)
                              
                            texts <- texts %>% html_text() %>% str_trim()
                          })
        
        # Get all known issue tag nodes
        tag_nodes <- read_excel("nodes.xlsx") %>% filter(element=="tags")
        
        tags <- c()
        tag <- NA

        # Try each known node for each press release
        # This is slow but not every press release will have a tag so can't
        # easily find node with node_hunter like other elements
        for(p in pr_links){
          for(i in 1:nrow(tag_nodes)){
            if(tag_nodes$type[i]=="css"){
              tag <- try(read_html(p) %>% html_elements(tag_nodes$string[i]),
                          silent=T)
            }
            else{
              tag <- try(read_html(p) %>% html_elements(xpath=tag_nodes$string[i]),
                          silent=T)
            }
            if(length(tag)!=1){
              if(length(tag)==0) tag <- NA
              else tag <- paste(tag, collapse=";")
            }
            else if(!inherits(tag, "try-error") | !is.na(tag) | 
               !identical(tag, character(0))){
              tag <- tag %>% html_text() %>% str_trim()
              break
            } 
            else tag <- NA
          }
          tags <- c(tags, tag)
        }

        # Add everything to the data frame
        pressers <- bind_rows(pressers, 
                          data.frame(date=dates[desired_dates], 
                                     title=titles, body=texts, 
                                     tags=tags, url=pr_links))
        }
      }
  
  return(pressers)
}

# info <- node_hunter(link="barrymoore.house.gov", debug=T)
# 
# member_scraper(info=info,
#                start_date="2024-12-01", end_date="2024-12-31",
#                            pressers=data.frame(date=c(), title=c(), body=c(),
#                                                tags=c(), url=c()),
#                            debug=T, progress=T)

```

## Main scraping function
```{r}
# Main scraping function
presser_scraper <- function(links, start_date, end_date=Sys.Date(), 
                            clean_text=F, page_limit=1000, debug=F,
                            progress=T, remove_duplicates=F,
                            log_fails=T){
  
  if(start_date > end_date) stop("Start date is after end date")
  
  pressers <- data.frame(date=NA, title=NA, body=NA, 
                         tags=NA, url=NA)

  if(!is.null(names(links))){ 
    pressers <- data.frame(name=NA, date=NA, title=NA, body=NA, 
                           tags=NA, url=NA)
  }
  
  if(log_fails) fails <- data.frame(URL=c(), error_message=c())
  
  for(i in seq_along(links)){
    scraped <- try(member_scraper(info=node_hunter(links[[i]], debug), 
                                  start_date=start_date, end_date=end_date, 
                                  page_index=0,
                                  pressers=pressers, page_limit=page_limit, 
                                  clean_text=clean_text, 
                                  debug=debug, progress=progress), 
                   silent=T)
    
    if(inherits(scraped, "try-error")){
      message("Scraping failed for: ", links[[i]])

      if(log_fails) fails <- bind_rows(fails, 
                                   data.frame(URL=links[[i]], 
                                              error_message=scraped[1] %>% 
                                                str_trim()))
    }
    else if(nrow(scraped)==0){
      message("No pressers found for: ", links[[i]])
      
      if(log_fails){
        fails <- bind_rows(fails, 
                           data.frame(URL=links[[i]], 
                                      error_message="No pressers found in date range"))
      }
    }
    else if(!is.null(names(links))){
      pressers <- bind_rows(pressers, scraped %>% mutate(name=names(links)[i]))
    }
    else pressers <- bind_rows(pressers, scraped)
  }
  
  if(log_fails){
    write.csv(fails, "fails.csv", row.names=F)
    message(nrow(fails), " failure(s) logged in fails.csv")
  }
  
  row.names(pressers) <- NULL
  
  if(remove_duplicates) pressers <- distinct(pressers)
  
  return(pressers)
}

# presser_scraper(links=c(Schweikert="schweikert.house.gov",
#                         Barry="barrymoore.house.gov"),
#                 start_date="2025-01-01",
#                 end_date=Sys.Date(), 
#                 debug=F, progress=T)

presser_scraper(links=c(Rogers="mikerogers.house.gov"),
                start_date="2025-01-01",
                end_date=Sys.Date(),
                debug=T, progress=T)

read_html("https://mikerogers.house.gov/news/documentquery.aspx?DocumentTypeID=27&Page=1") %>% 
  html_elements("")
```

## Getting House links
```{r}
house_links <- read_html("https://www.house.gov/representatives") %>% 
  html_elements(".views-field-value-5 a") %>% 
  html_attr("href") %>% 
  sapply(FUN=function(x) sub("(house\\.gov).*", "\\1", x)) # Clean junk tacked on the end

house_names <- read_html("https://www.house.gov/representatives") %>% 
  html_elements(".views-field-value-5 a") %>% 
  html_text() %>% str_trim()

names(house_links) <- house_names
```

```{r}
test <- presser_scraper(links=house_links[1:20],
                        start_date="2025-01-01",
                        end_date=Sys.Date(), 
                        debug=F, progress=T)
```




```{r}
read_html("https://schweikert.house.gov/category/congress_press_release/") %>% html_elements(".title a") %>%
  html_attr("href")

read_html("https://barrymoore.house.gov/media/press-releases/rep-barry-moores-bill-deport-illegals-who-drive-under-influence-passes-house") %>% html_node(".evo-press-release__body") %>% html_text()


# EXAMPLE ISSUE TAG
read_html("https://palmer.house.gov/media-center/press-releases/palmer-bill-reverse-biden-harris-doe-rule-passes-house") %>% html_node(".evo-press-release__field-evo-issues") %>% 
  html_text() %>% str_trim()


info

temp <- read_html("https://barrymoore.house.gov/media/press-releases") %>% 
  html_elements(".font-weight-bold a")

read_html("https://barrymoore.house.gov/media/press-releases/media/press-releases/rep-barry-moore-supports-continuing-resolution-deliver-relief-producers-and") %>% html_element(".evo-press-release__body") %>% html_text()


temp <- try(read_html("https://obama.house.gov"))

temp[[1]] %>% str_trim()
```

https://barrymoore.house.gov/media/press-releases/rep-barry-moore-supports-continuing-resolution-deliver-relief-producers-and
https://barrymoore.house.gov/media/press-releases/media/press-releases/rep-barry-moore-supports-continuing-resolution-deliver-relief-producers-and

TODO: FIND MORE NODES FOR ISSUE TAGS

TODO: MAYBE ADD OPTION TO NOT SCRAPE TAGS SINCE IT'S O(N^2)

TODO: EXTRACT NAME, DISTRICT FROM WEBPAGE OR PRESSER TEXT, AT LEAST LAST NAME FROM URL

TODO: FIGURE OUT RUNNING ID SYSTEM
